version: "1"

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: "Scan Python files and apply ToolStrategy wrapper"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "python"

