version: "1"

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: "Rename 'agent' to 'model' in streaming event filters"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "python"

