version: "1"
name: langchain/create-react-agent-to-create-agent
nodes:
  - id: transform
    name: transform
    js-ast-grep:
      js_file: scripts/codemod.ts
      include:
        - "**/*.py"
      exclude:
        - "**/test_*.py"
        - "**/*_test.py"
        - "**/tests/**"
        - "**/__pycache__/**"
        - "**/venv/**"
        - "**/.venv/**"
