version: "1"

nodes:
  - id: apply-transforms
    name: Transform .text() to .text property
    type: automatic
    steps:
      - name: "Scan Python files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "python"

