version: "1"

nodes:
  - id: apply-transforms
    name: Transform SystemMessage to string in agent calls
    type: automatic
    steps:
      - name: "Transform SystemMessage(content=...) to string in create_agent/create_react_agent"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "python"
          semantic_analysis: workspace

