version: "1"

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: "Scan python files and migrate langchain imports to langchain_classic"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "python"

