version: "1"

nodes:
  - id: apply-transforms
    name: Unwrap ToolNode in create_agent/create_react_agent calls
    type: automatic
    steps:
      - name: "Scan Python files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "python"

